- name: Update NodeJs and NodeRED
  shell: "update-nodejs-and-nodered"
  tags:
    - initConfiguration

- name: Install additional node for tp-link smart plugin
  shell: "cd $HOME/.node-red && npm install node-red-contrib-tplink-smarthome"
  tags:
    - initConfiguration

- name: Install additional node for wemo smart plugin
  shell: "cd $HOME/.node-red && npm install node-red-node-wemo"
  tags:
    - initConfiguration

- name: Install additional node for cron task management
  shell: "cd $HOME/.node-red && npm install node-red-contrib-cron"
  tags:
    - initConfiguration

- name: Install additional node for firebase storage
  shell: "cd $HOME/.node-red && npm install node-red-contrib-firebase-storage"
  tags:
    - initConfiguration

- name: Enable NodeRED service
  shell: "sudo systemctl enable nodered.service"

- name: Start NodeRED
  shell: "sudo systemctl start nodered"
  tags:
    - initConfiguration

- name: Wait for port 1880 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 1880
    delay: 10

- name: Stop NodeRED
  shell: "sudo systemctl stop nodered"

- name: Copy flows definition
  template:
    src: "flows.json.j2"
    dest: "{{ nodeRedFlowsDirectory }}/flows.json"

- name: Rename flows file
  shell: mv {{ nodeRedFlowsDirectory }}/flows.json {{ nodeRedFlowsDirectory }}/flows_`hostname`.json

- name: Start NodeRED
  shell: "sudo systemctl start nodered"

- name: Wait for port 1880 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 1880
    delay: 10
