- name: Update NodeJs and NodeRED
  shell: "update-nodejs-and-nodered"
  tags:
    - initConfiguration

- name: Enable NodeRED service
  shell: "sudo systemctl enable nodered.service"
  tags:
    - initConfiguration

- name: Start NodeRED
  shell: "sudo systemctl start nodered"
  tags:
    - initConfiguration

- name: Wait for port 1880 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 1880
    delay: 10

- name: Stop NodeRED
  shell: "sudo systemctl stop nodered"

- name: Install additional node for tp-link smart plugin
  shell: "cd $HOME/.node-red && npm install node-red-contrib-tplink-smarthome"
  tags:
    - initConfiguration

- name: Install additional node for wemo smart plugin
  shell: "cd $HOME/.node-red && npm install node-red-node-wemo"
  tags:
    - initConfiguration

- name: Install additional node for cron task management
  shell: "cd $HOME/.node-red && npm install node-red-contrib-cron"
  tags:
    - initConfiguration

# TODO: correct node-red-contrib-firebase-storage deps
# - name: Install additional node for firebase storage
#   shell: "cd $HOME/.node-red && npm install node-red-contrib-firebase-storage"
#   tags:
#     - initConfiguration

- name: Copy flows definition
  template:
    src: "flows.json.j2"
    dest: "{{ nodeRedFlowsDirectory }}/flows.json"

- name: Rename flows file
  shell: mv {{ nodeRedFlowsDirectory }}/flows.json {{ nodeRedFlowsDirectory }}/flows_`hostname`.json

- name: Start NodeRED
  shell: "sudo systemctl start nodered"

- name: Wait for port 1880 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 1880
    delay: 10

- name: Install BLE packages
  apt:
    pkg:
    - bc
    - bluez
    - bluez-hcidump
  install_recommends: yes
  become: true
  become_method: sudo
  tags:
    - initConfiguration

- name: Creates scripts directory
  file:
    path: ~/dev
    state: directory
  tags:
    - initConfiguration

- name: Checkout latest scripts from repository
  git:
    repo: 'https://github.com/ewojtach/RPiScripts.git'
    dest: ~/dev/RPiScripts

- name: Add executable flag to readTempAndMotionDetector
  file:
    path: ~/dev/RPiScripts/readTempAndMotionDetector.sh
    mode: u+x
  tags:
    - initConfiguration

- name: Add executable flag to rebootNodeRedScript
  file:
    path: ~/dev/RPiScripts/rebootNodeRedScript.sh
    mode: u+x
  tags:
    - initConfiguration

- name: Add executable flag to scanCronScript
  file:
    path: ~/dev/RPiScripts/scanCronScript.sh
    mode: u+x
  tags:
    - initConfiguration
